### ISSUE TITLE
Sending to the REPL immediately after connection uses `CL-USER` package

### ISSUE THREAD

**Issue by sjl** [l04m33/vlime#11]
99% of the time Vlime manages to autodetect the correct package for my Lisp buffers, but there's one case that trips it up.  If I start the Vlime server in another window (and quickload my project from there), then open (n)vim, connect with `\cc` and immediately try to send with `\ss` it will use the `CL-USER` package.  If I send again with `\ss` it works correctly, and if I open new buffers it also works.  It just seems to be that first time I try to send after connecting.

**Comment by l04m33** [comment]
I failed to re-produce this problem in my environments. To make it clear, I did it like this:

1. Start a server using `sbcl --load ~/quicklisp/setup.lisp --load vlime/lisp/start-vlime.lisp --eval (ql:quickload :clss)`;
2. `vim <clss source dir>/selector.lisp`;
3. `\cc`;
4. `\ss` on the first `defun`;
5. The compiler gave a warning on redefining `CLSS:MAKE-SELECTOR`, it means that `defun` was correctly evaluated in package `clss`.

Are these the same steps as how you produced this problem? If so, I may need more details. In particular:

* What were you sending with `\ss`? I presume you sent the same expression twice?
* In which file did you invoke `\ss`? It'll be nice if I can have a look at the content of that file.

Some implementation details: Vlime searches for an `(in-package ...)` form in the current buffer, and use that package if found. I'm suspecting the search failed to work with your file.

**Comment by l04m33** [comment]
Oops, I just recalled that I have fixed a similar bug a while ago, when tangling with issue #6.

When the REPL buffer is not open, sending anything to the REPL would cause the cursor to jump to the REPL buffer first, and (incorrectly) make the following evaluation calls to use the package bound to the REPL buffer, which defaults to `CL-USER`.

This is fixed in the master branch. Would you please check the version you are using, and maybe update the code and then see if the problem still exists?

**Comment by l04m33** [comment]
I'm closing this issue for now. If the problem ever rise again, please feel free to re-open this issue, or file another one.
