### ISSUE TITLE
Vlime didn't install properly

### ISSUE THREAD

**Issue by umnikos** [l04m33/vlime#29]
I'm using gvim on windows 7. I added vlime to my plugins and ran `:PluginInstall`. The plugin installed but none of the functionality is present, not even `:help vundle`. [Screenshot of issue](https://imgur.com/xMDfV4Y)

**Comment by HiPhish** [comment]
**EDIT:** Solved, it looks like Vim-Plug did not update the help tags correctly.

You need to add the `rtp` option:
```
Plugin 'l04m33/vlime', {'rtp': 'vim/'}
```
The Vlime repository has two parts: the server written in Common Lisp and the client written in VimScript, so you need to tell your plugin manager where inside the repo the actual Vim plugin is.

But since the topic is already up, I have the same problem when using Vim-Plug: https://github.com/junegunn/vim-plug
```
Plug 'l04m33/vlime', {'rtp': 'vim'}
```
It does show up in my runtime `&rtp`:
```
/Users/hiphish/.local/share/nvim/site-packages/vlime/vim/
```
and all the files are in that directory, yet nothing happens.

**EDIT:** I'm using Neovim in case that matters, but help files should work regardless.
**EDIT 2:** Same thing in Vim as well.

**Comment by qwertystop** [comment]
I'm on Neovim with Vim-Plug as well, but it worked for me (as far as getting help files up) with that same line. However, `<LocalLeader>rr`, though it starts the server in a new Vim split/window, fails to connect to it. `<LocalLeader>cc` also does not connect to the server, once started.

**Comment by qwertystop** [comment]
Scratch that, connection failure was a dependency error (lack of ncat) which I've fixed. Now it all appears to work. I'm on OSX, if it matters.

**Comment by MikeSperone** [comment]
Leaving a comment in case someone finds this on google like I did:

For Pathogen, even though it shouldn't be needed, I had to similarly add the Vlime's `vim` folder to my runtimepath.  I did that by adding this to my `.vimrc` file:
`set runtimepath+=$HOME/.vim/bundle/Vlime/vim`

or, more generically:
`set runtimepath+=<path/to/Vlime>/vim`
