### ISSUE TITLE
Installation issues on MacOS with Pathogen

### ISSUE THREAD

**Issue by ab-10** [l04m33/vlime#67]
# Issue

Running `sbcl --script ~/.vim/bundle/vlime/lisp/start-vlime.lisp` produces the following error:

```
While evaluating the form starting at line 29, column 0
  of #P"/Users/seneca/.vim/bundle/vlime/lisp/load-vlime.lisp":
Unhandled VLIME::QUICKLISP-NOT-FOUND-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                        {1004A88203}>:
  Quicklisp not found. Please set up Quicklisp or install the dependencies for VLIME manually.
```
[Full error backtrace](https://github.com/vlime/vlime/files/7487003/vlime_err.log)

# System

Vim 8.2 (w/ +channel)

ASDF 3.3.1

Quickstart latest version (I've verified installation by running `(ql:quickload "vecto")` in a fresh SBCL REPL).

SBCL 2.1.9

**Comment by phmarek** [comment]
`sbcl --script` won't use `.sbclrc`, and so `QL` won't be loaded already.

You either need to use `sbcl --load` instead, or configure your own command to start `sbcl`; see `:help g:vlime_cl_impl` within `Vim`, and/or the `vlime` function `vlime#server#BuildServerCommandFor_sbcl`.

I'll keep that issue open for now, so that you can report whether that's working for you.

**Comment by ab-10** [comment]
Thank you for correcting the `sbcl` command, the command executed successfully, but running `:help vlime` in vim fails regardless.

Could you please suggest what I should do?

**Comment by ab-10** [comment]
nvm, had to run `:Helptags`.
